### ISSUE TITLE
Wants more detail about for presto benchmark suite.json

### ISSUE THREAD

**Issue by PranayMunshi1982** [prestosql/presto#1220]
Hi friends,
I am running presto benchmark driver "presto-benchmark-driver.jar". It requires "suite.json' as config files to run the particular query on a particular schema. 
I can see two JSON elements in suite.json i.e. **1. file_formats 2. legacy_orc.** 

Here I am not able to understand the difference between two. Why we have these two elements, what is the significance of these two?

I can put required detail in first element and run the benchmark. 
When should I go for 'file_formats' and when should I go for 'legacy_orc'?
Which JSON attribute I should put in which JSON element?

Do we have more JSON elements for 'suite.json' in order to run benchmark?

@dain

**Comment by dain** [comment]
I assume you are referring to the example in this documentation: https://prestosql.io/docs/current/installation/benchmark-driver.html

The two names there, `file_formats` and `legacy_orc`, are simply names of the two test suites.  In that example, both suites are running the same queries in the same schema, but have different session properties.  Specifically, one of them is running with the default ORC reader and the other one is running with the old ORC reader, because this example was to show the improvements in the new ORC reader.

**Comment by PranayMunshi1982** [comment]
Thanks @dain . You are right I am following this only. 
Thanks for quick resolution.
