### ISSUE TITLE
I connected hive 3.1 times incorrectly 

### ISSUE THREAD

**Issue by majiajue** [prestosql/presto#1341]
setting：

connector.name=hive-hadoop2
hive.metastore.uri=thrift://slave1:9083
hive.config.resources=/home/bigdata/installed/presto/presto-server-317/etc/catalog/hadoop/core-site.xml,/home/bigdata/installed/presto/presto-server-317/etc/catalog/hadoop/hdfs-site.xml

![image](https://user-images.githubusercontent.com/128642/63361813-67cbb600-c3a3-11e9-9868-870318b685fa.png)

I have configured in hive -site.xml:

hive.support.concurrency=false;
hive.txn.manager=org.apache.hadoop.hive.ql.lockmgr.DummyTxnManager;
hive.enforce.bucketing=false;
hive.exec.dynamic.partition.mode=strict;
hive.compactor.initiator.on=false;
hive.compactor.worker.threads=0;
Could you please help to solve it?

**Comment by findepi** [comment]
Hi @majiajue 

there are two issues visible on your screenshot (for the future, it would be better to paste plain text rather than a screenshot)

- failure related to `information_schema.tables` -- what query did trigger that?
- failure when reading from transactional tables -- this is in progress, see https://github.com/prestosql/presto/issues/576 & related PRs.
  - if you can build Presto from source, you can try https://github.com/prestosql/presto/pull/1034 out. It's not ready yet, but can help you get going.

BTW
there is the `#troubleshooting` channel on Presto Slack (https://prestosql.io/community.html) where it's often quicker to get help.

**Comment by findepi** [comment]
@majiajue Presto 319 is just released. It won't help you, but it will provide a much better failure message.
We're still working on proper support for insert-only and ACID tables. Please follow https://github.com/prestosql/presto/issues/576.
Also, i invite you to join the Presto Slack (https://prestosql.io/community.html). See you there!
