### ISSUE TITLE
Units (eg @MinDuration) not validated in plugin's Config class

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#1674]
`@MinDuration` works e.g. in `FeaturesConfig`,
but does not work e.g. in `CachingHiveMetastoreConfig`

**Comment by findepi** [comment]
Proposed solution (based on my guess as to what's the root cause):

1. split airlift units into `units` and `units-validation`
2. do not include `units-validation` in SPI classloader

**Comment by electrum** [comment]
The root cause is that `@MinDuration` and other validation annotations implement the Bean Validation API, but that API is not part of the plugin class loader, so the API is not visible to the Bean Validation implementation inside of the plugin.

There seem to three possible solutions:

1. Add `validation-api` to the SPI
2. Split validation out of `units`
3. Remove `units` from the SPI

---

Option 1 is problematic due to Bean Validation having multiple specification versions, etc. It could break any plugins using Bean Validation and cause other problems. This seems like going in the wrong direction.

---

Option 2 is backwards with existing users of `units` that use it with validation. They need to add an additional Maven dependency on `units-validation` (hopefully with the same version as `units`) and update the imports for the validation annotations. This is a minor inconvenience but would be nice to avoid.

---

Option 3 is backwards incompatible for existing plugins in a few ways:

* `ResourceGroup` and `ResourceEstimates` will replace `Duration` with `java.time.Duration` and `DataSize` with `long`. This would affect implementations of `ResourceGroupConfigurationManager`, and any implementations of `EventListener` that use the `resourceEstimates` property of `QueryContext`.
* `PropertyMetadata` has static factory methods for these types. We can move the methods to `presto-plugin-toolkit`, so they can be referenced there or trivially copied into a plugin.
* Existing packaged plugins will likely not contain the `units` JAR. Any plugins using `units` will need to remove the `provided` Maven scope. If the plugin is built using `presto-maven-plugin` and updated to use the new SPI dependency version, then `presto-maven-plugin` will fail the build if the wrong scope is used. Otherwise, users will get a `NoClassDefFoundError` when the plugin is used.

---

At this point, it seems that adding `units` to the SPI was a mistake. Removing it will cause some short term pain, but looks like the best long term outcome.

**Comment by findepi** [comment]
> Option 1 is problematic 

i agree.
I am against Option 1.

> Option 2 is backwards with existing users of units that use it with validation.

That's correct. This is why I want to bump the units version to 2.0 to signal backward incompatibility.
Option 2 is certainly feasible and not really hard to do.
> Option 3
> it seems that adding `units` to the SPI was a mistake. Removing it will cause some short term pain, but looks like the best long term outcome.

I am not convinced. `units` are useful and they are useful in SPI as well.

If we want to remove `units` from SPI, I would want to add a copy of `DataSize` (and maybe `Duration`) classes in SPI directly. 
(Outstanding issue is how to effectively convert from `units` DataSize to SPI DataSize.)



I still think option 2 is the best option.
