### ISSUE TITLE
Test QueryMonitor#createQueryStatistics

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#1724]
`QueryStatistics` has superficial test coverage.
For example, `io.prestosql.spi.eventlistener.QueryStatistics#getTotalRows` is being verified in `io.prestosql.execution.TestEventListener#testNormalQuery`, but most other properties are not. Thus the conversion done in `io.prestosql.event.QueryMonitor#createQueryStatistics` isn't really covered with tests.

Relates to https://github.com/prestosql/presto/pull/1719

**Comment by manupatteri** [comment]
@findepi Wondering if this issue is still valid or if it can be closed . I see that https://github.com/prestosql/presto/pull/3880 has already added tests covering  QueryStatistics. Just that recently test has moved to TestEventListenerWithSplits#TestEventListenerWithSplits and TestEventListenerBasic#testOutputStats.  Both them seem to be covering all methods of QueryStatistics.

**Comment by findepi** [comment]
@manupatteri indeed, this should be closed after that PR. Thanks!
