### ISSUE TITLE
Pull MongoDB data using Presto - date comparison in the where clause

### ISSUE THREAD

**Issue by sudheer8** [prestosql/presto#1781]
I need help in writing a query which has a date comparison in the where clause
select time from ob_prd.mdb.sik where
time BETWEEN timestamp ‘2019-10-16 00:00:00.000’ AND timestamp ‘2019-10-16 14:59:59.000’
This is an example query
but this is returning zero records
even though I see the records that matches the time
can anyone please help me with this

**Comment by findepi** [comment]
predicate pushdown in MongoDB seems weird (not to say “totally wrong”) for anything other than varchar, because we don’t have any type conversion in
https://github.com/prestosql/presto/blob/d37eddd6c20e9c285324cbd6532a33cc52db6425/presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoSession.java#L327-L339

**Comment by findepi** [comment]
I am tagging this as `good first issue`, but I would warn against attacking the problem for all data types at once.
Even though the issue is about `timestamp`, I'd recommend fixing `real` data type first.
