### ISSUE TITLE
Why columns in WHERE clause are not included in desiredColumns?

### ISSUE THREAD

**Issue by gzwl** [prestosql/presto#2148]
Hello, my presto version is 0.202 and the picture below is the relative code (ConnectorMetadata::getTableLayouts).
![屏幕快照 2019-11-29 下午4 37 50](https://user-images.githubusercontent.com/12934253/69855579-c370de00-12c6-11ea-8009-e999aa2012c3.png)

For example, the sql is "select sum(a) from metric where b > 1 group by c order by sum(d)".
Column a、c、d are in the desiredColumns .
But why the column b are not in the desiredColumns？

**Comment by findepi** [comment]
> why the column `b` are not in the desiredColumns？

It's because it need not be returned to the engine.
Consider a case when connector has some means of identified which pieces of data satisfy `constraint` without materializing `b` values.
For example, Hive connector can identify Hive partitions which match the predicate. But it doesn't need to return the partitioning column, since it's not going to be used later on.

(I am assuming this answers your question, so let me close the issue.)

BTW table layouts are deprecated since Presto 306 and we're migrating existing connectors not to use them.
We now use methods like `ConnectorMetadata#applyFilter` to pushdown constraint into a connector.

Please join the `#dev` channel on our slack https://prestosql.io/slack.html.
See you there!

**Comment by gzwl** [comment]
@findepi  Thanks for your reply！But i still have some problems.
I think desiredColumns are the columns that presto need to get from datasource, is this right?
If it is right, the unenforcedConstraints may contain some columns that are not in desiredColumns, so the filtered result may not be right？

**Comment by findepi** [comment]
(continued on slack @ https://prestosql.slack.com/archives/CFLB9AMBN/p1575343012109600)
