### ISSUE TITLE
Make https://prestodb.io/ deprecated

### ISSUE THREAD

**Issue by tqh** [prestosql/presto#2565]
https://prestodb.io/ and https://prestosql.io/ both look like official pages for Presto.
One has version 230 as latest release one has 328.

It is extremely confusing and doesn't help anyone. So either deprecate or redirect that old thing..

**Comment by findepi** [comment]
@tqh 

Almost all the Presto team (the creators, community, bigger & smaller contributors) works on prestosql.
However, technically speaking, prestodb remains maintained by Facebook. That's why the site remains up.

You can read more about this at https://prweb.com/releases/prweb16070792.htm and https://github.com/prestosql/presto/issues/380

We can chat further on the [Presto community slack](https://prestosql.io/slack.html).

**Comment by tqh** [comment]
Could you at least add a notice that you probably want the active maintained project. I spent three days working with the wrong info because of it. It is very unfriendly to your users.
