### ISSUE TITLE
Bump aws-sdk to 1.11.697

### ISSUE THREAD

**Issue by tooptoop4** [prestosql/presto#2614]
Fixes https://github.com/prestosql/presto/issues/1132

**Comment by peterulsteen** [comment]
I, too, would love to see the aws-sdk upgraded to at least 1.11.623.

I've got a simple Presto cluster deployed to Kubernetes via AWS EKS. I was hoping to use the[ EKS feature to grant an appropriate IAM role to the K8s service account](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) (rather than granting the role to the underlying EC2 nodes). However, according to[ this blog post](https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/) aws-sdk v1.11.623 is the minimum required.

Over the weekend, it appears that AWS updated their[ docs suggesting that v2.10.11 is now required](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html). I suspect this is because they're wanting to push version 2 of their Java SDK since it's a significant rewrite. Does it make sense to target updating to version 2 at this time?

**Comment by findepi** [comment]
@tooptoop4 @peterulsteen while conservative upgrade to 1.11.x is safer, we will eventually want to move to 2.x anyay.
Do you know of any reasons not to do this now?

cc @electrum

**Comment by tooptoop4** [comment]
just risk, if tests are comprehensive enough then v2 is even better

**Comment by electrum** [comment]
I think 2.x has many API changes for async and not everything is supported yet.

**Comment by tooptoop4** [comment]
Maybe some docs should be updated to mention that since Presto 318 release that Presto will run slower if there are proxies in environment variables for S3 backed tables

**Comment by electrum** [comment]
@peterulsteen According to that page, it's also available in version 1.11.704 of the SDK. @tooptoop4 do you want to try updating to the current latest, 1.11.739?

**Comment by tooptoop4** [comment]
@peterulsteen https://github.com/prestosql/presto/pull/3210
