### ISSUE TITLE
Implement limit pushdown for elasticsearch connector

### ISSUE THREAD

**Issue by martint** [prestosql/presto#2624]
Also, if limit is pushed down, we should be able to optimize the call to elasticsearch to either do it without a scroll (if the limit is smaller than the default scroll size), or limit the scroll size to the effective limit.

**Comment by Lewuathe** [comment]
It can be done by using `applyLimit` of the connector pushdown mechanism. Can I work on this issue?

**Comment by martint** [comment]
Go for it!

**Comment by Lewuathe** [comment]
@martint I have a question about the behavior of `applyLimit` in module test cases.

The following code to test limit pushdown fails due to invalid results set.

```
[ERROR]   TestElasticsearchIntegrationSmokeTest.testLimitPushdown:493->AbstractTestQueryFramework.assertQuery:130 For query:
 SELECT count(*) FROM limit_pushdown LIMIT 1
not equal
Actual rows (up to 100 of 1 extra rows shown, 1 rows in total):
    [3]
Expected rows (up to 100 of 1 missing rows shown, 1 rows in total):
    [1]
```

https://github.com/prestosql/presto/compare/master...Lewuathe:elasticsearch-apply-limit#diff-4092feeb5f862c91cbc177030d8d9d67R492-R494

```java
assertQuery("SELECT count(*) FROM limit_pushdown LIMIT 1", "VALUES 1");
assertQuery("SELECT count(*) FROM limit_pushdown LIMIT 2", "VALUES 2");
```

But this code succeeded.

```java
assertEquals(computeActual("SELECT * FROM limit_pushdown LIMIT 1").getRowCount(), 1);
assertEquals(computeActual("SELECT * FROM limit_pushdown LIMIT 2").getRowCount(), 2);
```

Alongside the debug, I have found `applyLimit` is not called properly in the test cases of `TestElasticsearchIntegrationSmokeTest.java`. Therefore, I doubted the Elasticsearch connector always returns full records regardless of given limit parameter. How can we make sure to call `applyLimit` so that it can return the correct result?

**Comment by martint** [comment]
Can you post the latest version of your change? That link seems to be broken.

**Comment by synhershko** [comment]
> do it without a scroll (if the limit is smaller than the default scroll size), or limit the scroll size to the effective limit.

FWIW, as long as the limit is a small number (e.g. up to 1000) it's better to not initiate a scroll at all in this case since scroll has overhead as well.

**Comment by martint** [comment]
Can you show me the output of EXPLAIN for the query that fails?

**Comment by Lewuathe** [comment]
Sorry, I misunderstood the behavior with `count` and `limit.  I thought LIMIT precedes COUNT but that's not true. LIMIT is not applied to the number of records counted in the following query because COUNT generates only one record.

```sql
SELECT COUNT(*) FROM tbl LIMIT 3;
```

Therefore, the LIMIT works correctly without any problem.
This is the PR. https://github.com/prestosql/presto/pull/2781

**Comment by Lewuathe** [comment]
As https://github.com/prestosql/presto/pull/2781 was merged, can we close this?

**Comment by martint** [comment]
Yes, let’s close this one. I’m going to open another issue to track the improvement discussed above regarding skipping scrolls altogether for small limits.
