### ISSUE TITLE
Add ALTER TABLE SET AUTHORIZATION

### ISSUE THREAD

**Issue by kokosing** [prestosql/presto#3052]
This is syntax allows to change the owner of the table object. It might be particularly useful for views, where privileges of owner are used to execute the query.

Related issues:
 - https://github.com/prestosql/presto/issues/2625
 - https://github.com/prestosql/presto/issues/2974

CC: @lhofhansl

**Comment by lhofhansl** [comment]
I don't think that is needed, since access to tables is controlled by GRANT/REVOKE.

**Comment by kokosing** [comment]
I see. However, I was considering this for views specifically. Notice that when user executes views, he access tables (or other views) beneath only when view owner has grantable privileges to these tables. Also this might affect what column masks and row filters will be applied.

@martint WDYT?

**Comment by amiorin** [comment]
We need this feature at Zalando. Hive 3 supports [OWNER_TYPE](https://github.com/apache/hive/blob/632ce66cd4d6faafa50cb1d5dbda6a09f724d440/standalone-metastore/metastore-server/src/main/sql/mysql/hive-schema-3.0.0.mysql.sql#L622) for table. This is useful for teams so that anybody can drop tables. The view authorization use case like @kokosing said applies to us too.

**Comment by JamesRTaylor** [comment]
We need this at Lyft as well. Sometimes one user will create a table and would like to allow other user(s) to drop it. Is there a workaround for this currently?

**Comment by kokosing** [comment]
@lhofhansl Would you like to work on this?

**Comment by hitejinder** [comment]
Any update on this?

**Comment by kokosing** [comment]
Not yet. We are still looking for a volunteer to work on this.
