### ISSUE TITLE
Mongo connector does not drop table/collection

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#3082]
* `MongoQueryRunner.main()`
* ```
  use mongo.local;
  create table y(a bigint);
  show tables;
  drop table y;
  show tables;
  ```

-- this succeeds, but the `y` table is still there.

**Comment by ebyhr** [comment]
This method is the root cause. MongoDB CREATE TABLE doesn't create a collection `mongo.local.y`, but it saves the metadata to `_schema`. 
https://github.com/prestosql/presto/blob/3966b40ba11382f9ef7c706bdb8afd853f9b2b43/presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoSession.java#L449-L463
