### ISSUE TITLE
Get query string by QueryId

### ISSUE THREAD

**Issue by ertanyildiz** [prestosql/presto#3222]
Hey! I am developing a connector using `PRESTO SPI`. I just need to get the query string that the user executes on Presto. I can get `queryId` but no query string supplied from SPI.  Can you show me a way to get the query string? Thanks.

**Comment by findepi** [comment]
Original query string is not exposed to the connector.
This is an intentional decision. We want connectors to have well defined API and be isolated from each other, so each gets all the information and only the information that pertains this connector.

Let me close this issue as answered.
I encourage you to join the #dev channel on our slack https://prestosql.io/slack.html to discuss the problem you're trying to solve.

**Comment by kokosing** [comment]
Side note, the only way to get query string by the Presto plugin is to implement Event Listener.

**Comment by ertanyildiz** [comment]
> Side note, the only way to get query string by the Presto plugin is to implement Event Listener.

you are right. I can get the queries from EventListener. Thank you!
