### ISSUE TITLE
SQL `select * from table having 1=1;` throw exception saying first column not in GROUP BY clause

### ISSUE THREAD

**Issue by prestosql-history-doc** [prestosql/presto#3298]
We recently upgraded from 310 to 330.
`select * from table having 1=1;` 
This SQL used to work in 310 but throw exceptions in 330 saying "first column not in GROUP BY clause"

**Comment by martint** [comment]
This is expected behavior. If a query contains a HAVING clause but no GROUP BY clause, GROUP BY () is implied. In your example, this is equivalent to:

SELECT *
FROM t
GROUP BY ()
HAVING 1=1

Since the columns derived from * are not in the GROUP BY clause and are not aggregations, the query is invalid.

**Comment by prestosql-history-doc** [comment]
Noted with thanks.

**Comment by prestosql-history-doc** [comment]
Hi @martint, a follow-up question, why should `GROUP BY ()` implies in such condition?  In version 310,  this is just the same as the `WHERE` clause. Any reasons behind this change?
