### ISSUE TITLE
Support spill over when writing sorted data in hive buckets

### ISSUE THREAD

**Issue by gauravphoenix** [prestosql/presto#3410]
Most applications can easily generate partitioned data files and upload them directly to s3. Presto can directly query these files. However, for performance reasons, it is often highly desirable to bucket the data. Further, if the bucketed data is sorted, the performance will be even better. 

For example, let us say that we have a source table `data` with schema (`CREATE TABLE data (value string )`) and we want to create an optimized version of the table (`data_bucket`) which has bucketing enabled (`CREATE TABLE data_bucket  (value string) WITH (external_location='s3n://bucket-name/',format = 'orc',bucketed_by=ARRAY['value'],sorted_by=ARRAY['value'],bucket_count=1024) `)

Now if we try to run the query (`insert into data_bucket (select * from data)`) the query will likely fail if the cluster doesn't have enough memory. The error will resemble like this

```
Query exceeded per-node total memory limit of 8GB [Allocated: 7.91GB, Delta: 107.28MB, Top Consumers: {TableWriterOperator=7.83GB, ExchangeOperator=36.46MB, LazyOutputBuffer=32.13MB}]
```
This happens because Presto is sorting the data in memory before writing it to the target table. 

It would be great if the [spill over functionality](https://prestosql.io/docs/current/admin/spill.html) is supported for hive table writing

**Comment by electrum** [comment]
Writing sorted bucketed tables already uses spilling. The data is written to sort temporary files on the target file system (related #2301 to allow using local disk). The sort buffer size is controlled by `hive.writer-sort-buffer-size` which defaults to 64MB. These files are then merged together, possibly in multiple passes.

The total distributed memory requirement will thus be 64MB * 1024 (bucket count) for sorting. You'll also need memory for the 1024 ORC file writers, which is primarily controlled by `hive.orc.writer.stripe-max-size` which also defaults to 64MB. Thus, in total, you would need around 128GB, which is less than the available memory on a single, typical 256GB machine.

Rather than reducing the buffer sizes, which have drastics effects on performance, I recommend adding a few more machines or using instance types with more memory. An 8GB per-node query limit seems low for a write-heavy workload. Remember that you're optimizing for throughput. If you use small buffers and have to spill everything, the jobs will run for much longer -- it's cheaper to use larger machines for less time.

I'm happy to discuss this further on Slack: https://prestosql.io/slack.html

**Comment by gauravphoenix** [comment]
awesome, thanks @electrum . I will play with the configuration options.
