### ISSUE TITLE
After the EQUAL operation is overwritten, Slice and long are used, and the latter bit is EQUAL to 8 bits to report an error #14519

### ISSUE THREAD

**Issue by qianmoQ** [prestosql/presto#3726]
Version: 0.221

After the EQUAL operation is overwritten, Slice and long are used, and the latter bit is EQUAL to 8 bits to report an error!

source code

```java
@ScalarOperator(value = EQUAL)
    @SqlType(StandardTypes.BOOLEAN)
    public static boolean equal_string(@SqlType(StandardTypes.VARCHAR) Slice left, @SqlType(StandardTypes.BIGINT) long right) {
        return left.toStringUtf8().equals(String.valueOf(right));
    }
```

query sql:

```sql
select * from push_user_list_sms where ymd=20200511 limit 1
```

table desc:

Column | Type 
-- | -- | 
uid | bigint |
ymd | varchar|

ymd is hive Partition the primary key

get errors:

```java
Query failed (#20200513_023554_00007_e7mu7): Object 'Slice{base=[B@d146d99, address=16, length=8}' does not match type long
````
right length > 8  and right < 8 no problem

**Comment by findepi** [comment]
@qianmoQ an operator like equality (`=`, `OperatorType.EQUAL`), needs to operate on values of the same type (https://github.com/prestosql/presto/issues/3728)
If you want to compare varchar and numerical values, in SQL this would correspond to a "coercion".
Instead of defining a `varchar / bigint` EQUAL operator, you would modify coercion rules. 
(In the code, this corresponds to `io.prestosql.type.TypeCoercion#coerceTypeBase`).

Having said that, please be aware that lack of coercion from integer/bigint to varchar is not an omission, but a deliberate choice.
Having such a coercion may look like usability improvement for users, and some database systems allow that,
but it may also lead to hard-to-understand behaviors. Let me know if you would like to learn more about this design choice.

Let me close this as answered. We can continue discussion here, but i encourage you to join [our slack](https://prestosql.io/slack.html).
See you there!
