### ISSUE TITLE
Use python:slim as the base docker image and install JRE instead of JDK

### ISSUE THREAD

**Issue by ssquan** [prestosql/presto#3855]
The current size of the docker image is about 1G, it's a little bit big for production. I have two suggestions:

1. Change the base docker image from centos to python:3-slim. Slim is smaller than Centos and many systems use it in the production environment.
2. Use JRE instead of JDK.

I have tested locally, the size of image will be 760M after these two changes.

By the way, we can use docker multi-stage to build images instead of running a command to install packages:
```
FROM python:3-slim

COPY --from=openjdk:11-jre-slim /usr/local/openjdk-11 /usr/local/openjdk-11

ENV JAVA_HOME /usr/local/openjdk-11
ENV PATH $JAVA_HOME/bin:$PATH
```
It's easier to use ` python:3-slim` as the base image and copy JRE from `openjdk:11-jre-slim ` than vice versa.

**Comment by martint** [comment]
What image are you looking at? The size of recent images is ~600 MB according to dockerhub: https://hub.docker.com/r/prestosql/presto/tags

Regarding the use of JRE, Presto needs a full JDK, so that probably won't work. Also, the JRE is being phased out -- there are no public builds of a JRE anymore (that I can find, aside from that docker image), and in the future, Oracle may even stop producing those. See https://stackoverflow.com/questions/53111921/how-to-get-java-11-run-time-environment-working-since-there-is-no-more-jre-11-fo

**Comment by ssquan** [comment]
@martint  Thanks. 

the size of images is ~600M after compression and 1.03G before compression.
```
foodeMacBook-Pro:docker foo$ docker images | grep prestosql | grep 333
prestosql/presto                                   333                 5adc7a4d7326        3 weeks ago         1.03GB
```

OpenJDK is ~300M, Presto is ~450M, and OS is ~300M. it's reasonable, I will close this issue.

**Comment by electrum** [comment]
If you want to build your own image, you can remove connectors you don’t use, start with a smaller OS image, etc. We use a standard CentOS image since it’s generic and makes it easier to install debug tools or modify as needed. The provided Docker image is meant to be useable by anyone, especially  for demos or getting started, not optimized for any specific use case.

Don’t use Alpine or similar, as the Hadoop native code for the Hive connector requires glibc based Linux distributions.
