### ISSUE TITLE
"Query not found" clicking on query details in web UI even with "Query Rules - view" rule

### ISSUE THREAD

**Issue by tooptoop4** [prestosql/presto#3872]
I have query_rules.json:
```
    {
  "catalogs": [
    {
      "allow": true
    }
  ],
  "queries": [
    {
      "user": "mysuperacc",
      "allow": ["execute", "kill", "view"]
    },
    {
      "allow": ["execute"]
    }
  ]
}
```

access-control3.properties:
```
access-control.name=file
security.config-file=/home/ec2-user/presto-server-333/etc/query_rules.json
```

config.properties:
```
access-control.config-files=/home/ec2-user/presto-server-333/etc/access-control3.properties
```

I have verified that:

1. userA can:
  

- only see their own queries in system.runtime.queries
- only see their own queries in list on web UI
- clicking on queryid in web UI to get more details for their queries works

2. mysuperacc can:
-  see all queries in system.runtime.queries
-  see all queries in list on web UI 
-  BUT when clicking on queryid in web UI to get more details they can only see details for queries they ran, **not for the queries userA ran (get "Query not found" message)**. note: these are fresh queries not expired after 1 hour

![notfound](https://user-images.githubusercontent.com/33283496/83139151-d16fb200-a0e3-11ea-935c-0db0431f8fc8.png)

cc @dain

**Comment by tooptoop4** [comment]
maybe ranger issue

**Comment by aakashnand** [comment]
@tooptoop4 I figured out the root cause of this problem. When you log in to WebUI using `super-user` and click queryid of `userA` as `super-user`. The `super-user` tries to impersonate as `userA` and tries to get access to resources of `userA` in this case "query details". So when you get this messages `Query Not Found`, you will be able to see the `Denied` entry of the audit log on Ranger Audit section. 

So to solve this add your superuser to Trino Policy on Ranger under the `all-trinouser` section.
![image](https://user-images.githubusercontent.com/14219201/115939029-a77f6500-a4d7-11eb-93e0-3bf48dc7cfef.png)
