### ISSUE TITLE
Support for custom DynamicConfigurationProvider

### ISSUE THREAD

**Issue by chongfeng-hu** [prestosql/presto#3927]
Apologies if I missed anything... I notice that presto already supports a few mechanisms to customize S3 credentials:

1. [Custom S3 Credentials Provider](https://prestosql.io/docs/current/connector/hive.html#custom-s3-credentials-provider): this allows a custom credential provider, which provides the S3 credential regardless of user identity;

2. [S3 Security Mapping](https://prestosql.io/docs/current/connector/hive.html#s3-security-mapping): this allows a per-user-identity S3 credential, but given a user-identity, the corresponding S3 credential is static.

We have a use-case where the S3 credential provider is encapsulated into a service (a.k.a., permission service). The permission service takes a user identity, and emits an S3 credential (access-key, secret-key, session-token). The S3 credential will be rotated & refreshed, so it cannot be statically configured.

What are people's opinions if we propose to expand the mechanisms 1 and 2 above, by allowing people to provide a custom [DynamicConfigurationProvider](https://github.com/prestosql/presto/blob/master/presto-hive/src/main/java/io/prestosql/plugin/hive/DynamicConfigurationProvider.java) implementation?

To be more specific, we can add a new flag, e.g., hive.s3.dynamic-configuration-provider, which points to a fully qualified class name of a custom DynamicConfigurationProvider implementation. Then have [HiveS3Module](https://github.com/prestosql/presto/blob/master/presto-hive/src/main/java/io/prestosql/plugin/hive/s3/HiveS3Module.java) bind to this implementation.

As one example of such an implementation, [updateConfiguration](https://github.com/prestosql/presto/blob/master/presto-hive/src/main/java/io/prestosql/plugin/hive/DynamicConfigurationProvider.java#L25)(Configuration configuration, HdfsContext context, URI uri) will grab user-identity from context, call out to the permission service, obtain the S3 credential, and set it in configuration.

**Comment by electrum** [comment]
I'd rather not expose `DynamicConfigurationProvider` as it's tightly coupled to the Hive connector APIs and we have some plans to change or remove it. I think what you want can be done today with the custom credentials provider mechanism.

Set `presto.s3.credentials-provider` to a class name in the Hadoop configuration. This isn't currently exposed as a Hive connector config -- you have to set it in the Hadoop XML directly and load these via the Hive connector `hive.config.resources` config property. We could expose this with a Hive connector configuration property if needed, but since the credentials provider gets its configuration from the Hadoop configuration anyway, it seems likely you'll need to set `hive.config.resources` anyway. It's trivial to add the Hive connector config if this is helpful.

This class needs to implement `com.amazonaws.auth.AWSCredentialsProvider` and have a constructor that takes `(java.net.URI, org.apache.hadoop.conf.Configuration)`.

Since accessing the user requires impersonation, you need to set the Hive config property `hive.hdfs.impersonation.enabled=true`. Then you can use `org.apache.hadoop.security.UserGroupInformation` to get the user in your credential provider.

**Comment by electrum** [comment]
Join [Slack](https://prestosql.io/slack.html) and ask in the `#dev` channel if you want to chat about this.

**Comment by chongfeng-hu** [comment]
Thanks for the pointer! A few follow-up questions:

1. `presto.s3.credentials-provider` requires a class that implements [AWSCredentialsProvider](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/AWSCredentialsProvider.html). AWSCredentialsProvider only provides the pair of (access-key, secret-key), but our permission provides a triplet of (access-key, secret-key, session-token), and the session token is critical to be passed to S3. [AWSSessionCredentialsProvider](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/AWSSessionCredentialsProvider.html) instead would fit our requirement well;

2. If we enable HDFS impersonation, what user-identity will be available from UserGroupInformation? According to [doc](https://prestosql.io/docs/current/connector/hive-security.html#impersonation-accessing-hdfs), the user-identity is argument to the --user option, but searching through presto code base, I couldn't find anywhere that plumbs this user name into UserGroupInformation. Could you please share a pointer? Note that we are not using Kerberos, and we have no real Hadoop or HDFS running -- our Presto directly connects to S3 via the hive connector.

**Comment by electrum** [comment]
1. `AWSSessionCredentialsProvider` is a subclass of `AWSCredentialsProvider`, so I think this should just work. The internal `PrestoS3FileSystem.createAwsCredentialsProvider()` method already returns `STSAssumeRoleSessionCredentialsProvider` which is a `AWSSessionCredentialsProvider`, which makes me think it already works.

2. It will be the Presto user, which is set via `ImpersonatingHdfsAuthentication`. How it all fits together is quite complex, due to how Hadoop file systems work, but since this works already for HDFS it should also work for S3. From the Hive connector perspective, there is no difference between HDFS or S3 in this regard -- they are both just file systems with access to `UserGroupInformation`.

**Comment by chongfeng-hu** [comment]
Thanks a lot for the pointers!

**Comment by chongfeng-hu** [comment]
@electrum One more follow-up question:

As you mentioned, `presto.s3.credentials-provider` needs to implement `com.amazonaws.auth.AWSCredentialsProvider` and have a constructor that takes (`java.net.URI`, `org.apache.hadoop.conf.Configuration`). Given only these two constructor parameters, how do we obtain access to `UserGroupInformation` inside the `presto.s3.credentials-provider`?

**Comment by tooptoop4** [comment]
did u solve this @chongfeng-hu ? I guess this is good extension to https://github.com/trinodb/trino/pull/6102

**Comment by chongfeng-hu** [comment]
I ended up using the [Custom S3 credentials provider](https://trino.io/docs/current/connector/hive-s3.html#custom-s3-credentials-provider) that David had suggested, and it turned out to fit our needs nicely.

**Comment by tooptoop4** [comment]
can u share the class definition and properties? @chongfeng-hu

**Comment by chongfeng-hu** [comment]
```
public class YourCredentialsProvider implements AWSSessionCredentialsProvider {

    private final String userName;
    private final String yourOtherProperty;

    public YourCredentialsProvider(URI uri, Configuration configuration) {
        try {
            // userName is passed in as the impersonated user.
            this.userName = Objects.requireNonNull(UserGroupInformation.getCurrentUser().getShortUserName());
            this.yourOtherProperty = Objects.requireNonNull(configuration.get("your.other.property"));
            log.info(String.format("Initializing AwsCredentialsProvider for user [%s].", userName));
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    @Override
    public AWSSessionCredentials getCredentials() {
        // insert your custom logic to map from this.userName into an instance of AWSSessionCredentials.
    }
}
```
Build above into a stand-alone uber jar with all dependencies included, and place it under `plugin/hive-hadoop2`.

hive.properties
```
connector.name=hive-hadoop2
hive.config.resources=/path/to/your/core_site.xml
hive.hdfs.impersonation.enabled=true
hive.metastore.uri=...
...
```

core_site.xml
```
<configuration>
<property>
  <name>trino.s3.credentials-provider</name>
  <value>com.your.company.YourCredentialsProvider</value>
  <description>Custom S3 Credentials Provider</description>
</property>
<property>
  <name>your.other.property</name>
  <value>your_value</value>
</property>
</configuration>
```
