### ISSUE TITLE
JDBC driver consumes 100% CPU on a core since 325 release

### ISSUE THREAD

**Issue by tooptoop4** [prestosql/presto#3928]
All that time is being spent in Lio/prestosql/jdbc/PrestoResultSet$AsyncIterator;::hasNext

https://github.com/prestosql/presto/blob/334/presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoResultSet.java#L1815

https://github.com/prestosql/presto/pull/965#discussion_r330199981 has more details

**Comment by ebyhr** [comment]
Related Slack thread is https://prestosql.slack.com/archives/CGB0QHWSW/p1591256731318900

**Comment by findepi** [comment]
cc @ShashwatArghode

**Comment by lhofhansl** [comment]
Getting this right is pretty tricky. In addition to the current busy waiting in hasNext() I have a hard time convincing myself that we're not leaving threads hanging around (for example when the buffer is filled up, and nobody ever calls next/hasNext.

Maybe a simpler (slightly less performant) solution is to simply do pre-fetching. When a caller calls hasNext/next, we read a few more results from the passed iterator and the next calls would be served from the prefetch buffer.
We won't get the nice interleave of fetching and reading, but it'd be simpler and easier to reason about.

**Comment by lhofhansl** [comment]
But, I do not know what part is slow about the fetching. If it's the lazy fetching one-by-one, then prefetching should be good enough. Perhaps someone can shine some light on that.

Prefetching itself is trivial (untested):
```
    private static class PrefetchIterator<T>
            implements Iterator<T>
    {
        private static final int MAX_QUEUED_ROWS = 10_000;

        private LinkedList<T> rowQueue = new LinkedList<>();
        private Iterator<T> source;

        public PrefetchIterator(Iterator<T> dataIterator)
        {
            requireNonNull(dataIterator, "dataIterator is null");
            this.source = dataIterator;
        }

        @Override
        public boolean hasNext()
        {
            if (rowQueue.isEmpty()) {
                for (int i = 0; i < MAX_QUEUED_ROWS && source.hasNext(); i++) {
                    rowQueue.add(source.next());
                }
            }
            return !rowQueue.isEmpty();
        }

        @Override
        public T next()
        {
            return rowQueue.poll();
        }
    }
```

**Comment by lhofhansl** [comment]
FWIW, as a test I removed the AsyncIterator code; with everything on the localhost I see no slowdown.

With client and server on localhost we obviously have no networking latency. My data comes from Hive table (on a local HDFS)

For kicks I introduced a 10ms delay into my LOCAL network and still see no measurable difference in performance with or without the AsyncIterator.

So my question: What problem did we try to solve with #965 ?
- Network latency between server and JDBC client? (so that we can interleave the server iteration with client retrieval)
- Slow iterator for some of the connectors?

I think that #965 was not sufficiently motivated... At the very least I do not get what it is trying to achieve. Perhaps we should remove that code.

**Comment by electrum** [comment]
@lhofhansl I remember seeing a benchmark associated with the original PR, but I can't seem to find it now. @ShashwatArghode do you remember the use case that motivated this and the benchmark numbers?

**Comment by ShashwatArghode** [comment]
Thanks @findepi for cc-ing.
@electrum This was a general improvement over the previous Presto code and I think was asked by users as well. The benchmark was performed on an actual Presto cluster on HDFS back then and [this](https://github.com/prestosql/presto/pull/965#discussion_r294021918) is the link.

I was looking into possible solutions

Approach 1:
downloadSpeed_END_TOKEN.txt is the patch in accordance with your [#965 comment](https://github.com/prestosql/presto/pull/965#discussion_r330199981) and also followed some of [#2022](https://github.com/prestosql/presto/pull/2022/files#diff-7f2de85f7d593af7675d82431dc38327R73)

I think this patch will take care of queries that are erroring out but, we will have the same problem with slow running queries.

[downloadSpeed_END_TOKEN.txt](https://github.com/prestosql/presto/files/4768499/downloadSpeed_END_TOKEN.txt)

Approach 2: 
downloadSpeed_Wait:Notify.txt patch makes the hasNext() operation blocking. This will solve the busy loop problem but, this patch uses Thread.getState() and as per documentation this method is designed to be used for monitoring and not for synchronization control.

[downloadSpeed_Wait:Notify.txt](https://github.com/prestosql/presto/files/4768517/downloadSpeed_Wait.Notify.txt)

@electrum @findepi Do you think any of this approach makes sense or can you suggest any other approach which will help with this?

**Comment by electrum** [comment]
@ShashwatArghode Using `Thread.getState()` is not the right way, as you noticed. The "end token" approach seems like a good way. What do you mean about "same problem with slow running queries"?

I think part of the problem is that we don't have a reproducible benchmark. @ShashwatArghode would you be able to reproduce your original benchmark results using the TPC-H connector?

@lhofhansl do you want to put a PR with your change? Fixing the 100% CPU problem seems like the most important thing right now. Can you try benchmarking with TPC-H as well? It would be helpful to see what is different between the scenarios.

**Comment by lhofhansl** [comment]
@ShashwatArghode I looked into the token approach as well. It complex in the following scenario: The AsynchIterator filled it's blocking queue, the parent thread is interrupted, and the client is not reading from the iterator. In that case I could not convince myself on a good solution to guarantee the thread not hanging around indefinitely.

@r0hini I tried with 128m records reading in batches of 10k. But all on a single machine so that I can debug. I believe you that it was an improvement :)  Just figuring out what the problem is that we were trying to fix. Perhaps I do not see the effect.
Can you describe what exactly the AsyncIterator fixes? Is the problem the network RTT between the server and the JDBC client?

@electrum My change simply removes the AsyncIterator, it leaves everything else of #965 in place. I wanted to add prefetching, but then found that I cannot reproduce the problem even with artificially induced network latency.

**Comment by r0hini** [comment]
> But, I do not know what part is slow about the fetching. If it's the lazy fetching one-by-one, then prefetching should be good enough.
Since using separate threads for fetch and writing worked out really well for the CLI, we just went with the same approach for JDBC as well. Network latency wasn't the main reason even though it could be a factor if users were connecting via VPN and have poor wifi. Most of the time, it was the jdbc clients themselves being slow in processing a record and some custom clients were fetching using Presto and updating some KV stores. Prefetching solution you have proposed might also work in that case and I am good with that.

**Comment by lhofhansl** [comment]
Thanks @r0hini just asking because if the problem is the source iterator itself being slow - and hence we wanted it to fill a queue while the JDBC client is doing its processing - then prefetching might not be effective since it would still be done with the JDBC client waiting for the prefetching.

**Comment by r0hini** [comment]
@lhofhansl, you mentioned that you are not seeing any difference at all and thinking more on that, it does not sound right to me because the parallelization of fetching and parsing json in parallel should make some difference. Does you testing just loop through rs.next() without doing anything with the records or it at least has a print statement of each record? Can you give details of your benchmarking test, so that we can try reproducing?

**Comment by lhofhansl** [comment]
@r0hini Hmm... I only get a value of the resultset every 10.000th call to next(). I'll change it to retrieve a value each time.
(And for the record, I'm not saying the parallelization is not needed, I'm trying to figure out the scenario, in order to figure out whether it's possible to simplify the logic and avoid the busy wait. :) )

**Comment by lhofhansl** [comment]
Ok... Now when I introduce a 100ms (!) network delay I see about 25% improvement with the change.
I.e. ~1100ms to ~1400ms for 100k rows.

(again with 100k rows each time, and an artificial network latency of 100ms)

That is without and prefetching, just removing the AsyncIterator. I just cannot find a scenario that would justify the extra busy waiting.

**Comment by r0hini** [comment]
Intent was to speed up the total response time and since it was single threaded with laptops to servers hosting BI tools having more cores available, we decided to use separate threads for speeding up. One for fetch (both network time and compute time of parsing json http response->objects) and another for format/print (mainly compute time but possible that the custom jdbc user code involves some network time as well).  Can you also try tables with datatypes like timestamp and doing rs.getTimeStamp(). I think you will see more difference due to increased compute.

> I just cannot find a scenario that would justify the extra busy waiting.
Not disagreeing on that. We should definitely get rid of the busy wait and also address possible leaking of threads that you raised. If it takes more time to solve it right or come up with a better solution as Presto release cycles are very short, we can revert it for the next release and fix it again after that. If pre-fetching works we can go with that, but I now doubt that it will be as good as using more threads.

**Comment by lhofhansl** [comment]
Thanks @r0hini  I'll try with timestamps too.

We can wait for two conditions with a traditional Java monitor (Java synchronized). Each time we add something to queue or when the Future is done we `notify()`. On the other thread we just check the condition and wait() in a loop.  Problem is we'd have to enter and leave the monitor a lot (on the "sending" side, which at least need to perform a memory barrier, and that might negate the speed improvement). Or use a Semaphore (I assume that would have the same overhead as a monitor - mostly a memory barrier).

**Comment by lhofhansl** [comment]
I have a version with a counting Semaphore that does not busy looping. But all the synchronization overhead seems to outweigh the benefit. I see it taking about 1450ms/100.000 iterations. (simple getInt() still)

**Comment by lhofhansl** [comment]
Here's the change with the Semaphore... Pretty simple, just counts the number of expected rows in a Semaphore, and uses that to block.
```
diff --git a/presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoResultSet.java b/presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoResultSet.java
index cc874c41a4..c93ff4f22d 100644
--- a/presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoResultSet.java
+++ b/presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoResultSet.java
@@ -64,6 +64,7 @@ import java.util.concurrent.BlockingQueue;
 import java.util.concurrent.CompletableFuture;
 import java.util.concurrent.ExecutionException;
 import java.util.concurrent.ExecutorService;
+import java.util.concurrent.Semaphore;
 import java.util.concurrent.atomic.AtomicBoolean;
 import java.util.concurrent.atomic.AtomicReference;
 import java.util.function.Consumer;
@@ -1801,6 +1802,7 @@ public class PrestoResultSet
         private final StatementClient client;
         private final BlockingQueue<T> rowQueue = new ArrayBlockingQueue<>(MAX_QUEUED_ROWS);
         private final CompletableFuture<Void> future;
+        private final Semaphore s = new Semaphore(0);
         private Thread parent;
 
         public AsyncIterator(Iterator<T> dataIterator, StatementClient client, Thread parent)
@@ -1808,17 +1810,17 @@ public class PrestoResultSet
             requireNonNull(dataIterator, "dataIterator is null");
             this.parent = parent;
             this.client = client;
-            this.future = CompletableFuture.supplyAsync(() -> {
+            this.future = CompletableFuture.runAsync(() -> {
                 while (dataIterator.hasNext()) {
                     try {
                         rowQueue.put(dataIterator.next());
+                        s.release();
                     }
                     catch (InterruptedException e) {
                         interrupt(e);
                     }
                 }
-                return null;
-            }, executorService);
+            }, executorService).whenComplete((result, ex) -> { s.release(); });
         }
 
         public void cancel()
@@ -1836,14 +1838,14 @@ public class PrestoResultSet
         @Override
         public boolean hasNext()
         {
-            if (!rowQueue.isEmpty()) {
-                return true;
+            try {
+                s.acquire();
             }
-            while (rowQueue.isEmpty() && !future.isDone()) {
-                // making sure rowQueue has some records to process or return false
-                if (parent.isInterrupted()) {
-                    interrupt(new InterruptedException("parent thread interrupted"));
-                }
+            catch (InterruptedException e) {
+                interrupt(e);
+            }
+            if (parent.isInterrupted()) {
+                interrupt(new InterruptedException("parent thread interrupted"));
             }
             if (future.isCompletedExceptionally()) {
                 try {
```

**Comment by ShashwatArghode** [comment]
@electrum By slow running queries, I meant the datastore which is inherently slow in providing data to the iterator. In this case, we will busy loop until the data is available.

@lhofhansl, as @electrum suggested I used lineitem table from sf30 schema from the TPC-H catalog with single node (presto-coordinator + presto worker) locally. I did a `select *` on the table and just printed all values as a string on the console. (The tests were done without the end_token/wait_notify patch)

Total Rows: ~180M
Time-taken by new driver: 2595.97 seconds
Time-taken by the old driver: 3632.43 seconds

The results indicate that we are able to optimize the fetching of the query result with this approach, we need an efficient solution to avoid busy looping though. 

> I have a version with a counting Semaphore that does not busy looping. But all the synchronization overhead seems to outweigh the benefit. I see it taking about 1450ms/100.000 iterations. (simple getInt() still)

You can also run a similar benchmark to verify this.

**Comment by lhofhansl** [comment]
@ShashwatArghode Any chance that you could try with the simple Semaphore change above? (I'll be a bit busy in the next few days.)

When either source iterator or the network is slow the extra synchronization overhead should be absolutely negligible.

**Comment by findepi** [comment]
> If it takes more time to solve it right or come up with a better solution as Presto release cycles are very short, we can revert it for the next release and fix it again after that.

@r0hini  I think it is a good idea.
Would you like to do that?

**Comment by findepi** [comment]
@lhofhansl 
I am a bit surprised additional synchronization removes all the benefit from parallel work.
It could be in the case where "client app" (consumer of results) does very little, but should not be the case when client app does more work. 
This is not to say I reject you observations. I am a bit confused which scenario you were testing this against.

Also, if we have to reduce the overhead of synchronization, we could do hand over of batches, instead of individual rows, and then flatten this on the reading side
(this without additional synchronization).

**Comment by lhofhansl** [comment]
@findepi I am too, and I am now questioning my testing. The Semaphore change is simple and easy to reason about... should be good. Perhaps I'll do a PR...?

**Comment by lhofhansl** [comment]
Posted some number over in #4100
