### ISSUE TITLE
kerberos enabled connection failed

### ISSUE THREAD

**Issue by melin** [prestosql/presto#4311]
kerberos enabled, prestosql connection failed，prestodb connection success，Server configuration is the same

![image](https://user-images.githubusercontent.com/1145830/86321381-75acc180-bc6b-11ea-9a09-a47d0bbd850f.png)

![image](https://user-images.githubusercontent.com/1145830/86322020-bce78200-bc6c-11ea-9fab-e26b806683b9.png)

**Comment by kokosing** [comment]
Try to use `--user <YOUR_KRB_PRINCIPAL_HERE`.

PrestoSql by default disallows to impersonate to any user and with KRB authentication your user could be only set to the same value as your KRB principal. You can change how principal can be mapped to user with `http-server.authentication.krb5.user-mapping.pattern` and `http-server.authentication.krb5.user-mapping.file` configuration properties.  Please see more details: https://prestosql.io/docs/current/security/user-mapping.html

Notice that without this feature, if you got through authentication process and without properly configured system access control (via `access-control.properties) you could become any user which leads to privilege escalation (security hole).

I am closing this, because everything works as expected. In case you have more questions please do continue here, or via slack: https://prestosql.io/slack.html
