### ISSUE TITLE
Show Create View generates invalid view name.

### ISSUE THREAD

**Issue by kien-truong** [prestosql/presto#433]
When the user provide fully qualified view name in show create queries, generated result will output the wrong view name. For example

    show create view hive.a.b 

will result in

    create view b.a.hive

This is due to the following lines, which assume table name is `parts[0]`, while in fact it can be `parts[1]` or `parts[2]` (the last value) depending on the user's provided view name.

https://github.com/prestosql/presto/blob/b7aa1efa45fc87be03ddb24377b44415aa0d8e22/presto-main/src/main/java/io/prestosql/sql/rewrite/ShowQueriesRewrite.java#L434

**Comment by ebyhr** [comment]
Hi, thank you for reporting this issue. Are you interested in creating the PR?
`SHOW CREATE VIEW` is tested in below place. It currently passes since the catalog and schema are not specified.
https://github.com/prestosql/presto/blob/c31287fefc865ef539f7809f1da9d9b9bca2286a/presto-tests/src/main/java/io/prestosql/tests/AbstractTestDistributedQueries.java#L748

**Comment by kien-truong** [comment]
Sorry, I don't have time to create the PR for this now.

**Comment by Praveen2112** [comment]
@ebyhr can I raise a PR for the same. Sorry it was my mistake I didn’t reverse the list so it end up like that.

**Comment by ebyhr** [comment]
@kien-truong Okay. Your investigation is really helpful. We appreciated it.

@Praveen2112 Sure, go ahead.
