### ISSUE TITLE
Support role management

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#44]
Support Roles, Grants, etc.

**Comment by findepi** [comment]
https://github.com/prestodb/presto/pull/11645 -- this needs to be rebased.

**Comment by hustnn** [comment]
Will the role management be integrated with ranger or not?

**Comment by kokosing** [comment]
Ranger itself does not support roles, see https://docs.hortonworks.com/HDPDocuments/HDP2/HDP-2.6.5/bk_security/content/about_ranger_policies.html. Instead it provides:
 - policies which are using hierarchical pattern with wildcards to match resources
 - users and groups (where groups are defined in ANSI SQL)
 - different set of action that is defined in ANSI SQL

It does not look straithforward how Ranger authorization rules can be mapped to SQL role management.

**Comment by tooptoop4** [comment]
gentle ping

**Comment by martint** [comment]
@tooptoop4, this feature is already available since release 300.

**Comment by tooptoop4** [comment]
what is difference between prestosql and prestodb repos?

**Comment by shahabbadihi** [comment]
I believe this issue is still relevant today and would like to add a concrete
proposal based on current production use cases.

At the moment, Apache Ranger supports role-based authorization mainly at the
resource/data level. However, at the system access control layer — particularly
in RangerSystemAccessControl — there is no proper support for role-based
authorization, and decisions are typically based on users or groups.

In production environments where roles are the primary authorization abstraction,
this makes it difficult to express system-level permissions consistently.

It would be very useful to support roles at the system access control level as well.
Introducing an SPI for role resolution — similar to Trino’s GroupProvider interface —
could provide a clean and extensible solution, while keeping the core authorization
logic decoupled from identity management.

I’d appreciate any feedback on whether this aligns with Trino’s direction.
