### ISSUE TITLE
SPI Authenticator

### ISSUE THREAD

**Issue by ckdarby** [prestosql/presto#4767]
The JsonWebTokenAuthenticator is very close to what we'd like to achieve aside from the fact our code would like to add a group based off the JWT payload.

We've looked through the SPI and see PasswordAuthenticator & CertificateAuthenticator but JsonWebTokenAuthenticator isn't there nor the lower Authenticator class.

Any reason why the Authenticator itself isn't exposed in the SPI? Should it be? Are we missing something obvious?

**Comment by electrum** [comment]
Authenticator is not in the SPI since it has specific interactions with the HTTP protocol and we need to define a useful yet appropriate API. There has been some interest but never enough for someone to work towards solving it.

You can write a custom group provider: https://prestosql.io/docs/current/develop/group-provider.html

Decoupling it from authentication has some advantages. For example, views run as the owner, and thus require the groups to be provided separately.

For your goal, it seems like the easiest way to accomplish it is to add a config property for the name of a JWT claim to be used as the group list. The value could be a JSON list or a string with comma separated list.

**Comment by ckdarby** [comment]
@electrum Firstly thank you for taking the time to answer. If I follow correctly you're suggesting leaving JsonWebTokenAuthenticator untouched and handling the logic in a custom group provider.

Looking through the code I don't see ContainerRequestContext being passed to the GroupProviderFactory. I don't see a straight forward path to use the JWT claim in the Group Provider if the ContainerRequestContext isn't there to have the JWT claim itself.

If I'm missing something obvious let me know.

**Comment by electrum** [comment]
No, I’m suggesting you can implement a standard group provider that looks up the groups based on the user. It would be completely decoupled from JWT.

The other suggestion is that we could add group support to the existing JWT authenticator. This is a lot simpler than building an extensible mechanism, and allows anyone to use it without needing custom code.

**Comment by electrum** [comment]
This is what I was referring to about making groups available in views: https://github.com/prestosql/presto/issues/4543

**Comment by ckdarby** [comment]
> The other suggestion is that we could add group support to the existing JWT authenticator. This is a lot simpler than building an extensible mechanism, and allows anyone to use it without needing custom code.

This is probably the best option at least given my situation. For context, there are a lot of users added & removed. The current JWT authenticator in Presto adds a Presto user via the subject in the JWT claim which is unique. The mapping to do the custom group plugin would be quiet large and often stale as users get added & removed often.

Thanks. I'll look at adding a config property to the JWTAuthenticator for the name of the JWT claim to be used as the group list.
