### ISSUE TITLE
Simplify maven-enforcer-plugin/maven-dependency-plugin setup

### ISSUE THREAD

**Issue by iirekm** [prestosql/presto#4833]
The current setup makes too much hassle, too many build errors even after adding/changing single dependency.
The fact that there's no IntelliJ plugin for this and our Maven builds are slow (incremental builds don't work properly), makes it even more annoying.

IMHO all we need to solve issues with incompatible dependencies is:
```xml
<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-enforcer-plugin</artifactId>
        <version>1.4.1</version>
        <configuration>
            <rules><dependencyConvergence/></rules>
        </configuration>
</plugin>
```

Plus maybe generating dependency-lock.json file, widely popular in NodeJS - in Maven it could be done with  eg https://github.com/vandmo/dependency-lock-maven-plugin

This file can be used to fail build if it changes, and can be committed to Git, so we have full understanding and history of our classpath (now we have to list manually transitive dependencies in pom.xmls).

**Comment by electrum** [comment]
Have you tried `dependencyConvergence`? My understanding is that it requires every dependency to have the same version, which is more strict than our existing `requireUpperBoundDeps`. This means if a library depends on Guava 28, we can't update to Guava 29, even if it's compatible, until that library is updated. Am I misunderstanding how it works?

I like the idea of lock files, but that plugin uses a naive file format which is vulnerable to logical merge conflicts. The approach of [gradle-consistent-versions](https://github.com/palantir/gradle-consistent-versions#technical-explanation) is much better since it uses hashes to guarantee that logical conflicts result in a merge conflict.

**Comment by iirekm** [comment]
dependencyconvergemce / requireupperbounds or something similar - whatever
is enough for us 🙂. Now we have much, much more than that 😔

Maybe there's a Maven equivalent of this gradle-consistent-versions, if
not: dependency-lock.json is a nicely formatted json (each key: value pair
in new line), so merging/diffing it is not a problem.

I would even say that dependency-lock.json can be all we need: whole
classpath and its history is clearly visible in git or pull requests.

pt., 14 sie 2020, 19:10 użytkownik David Phillips <notifications@github.com>
napisał:
