### ISSUE TITLE
Implement ResultSet#getRow in JDBC driver

### ISSUE THREAD

**Issue by ebyhr** [prestosql/presto#5745]
Additionally, we may need to check other methods to allow running in Spring.

https://github.com/prestosql/presto/blob/96de404ec944d60e39c6f2175533066c6b1ff364/presto-jdbc/src/main/java/io/prestosql/jdbc/AbstractPrestoResultSet.java#L687

ResultSet#getRow https://docs.oracle.com/javase/8/docs/api/java/sql/ResultSet.html#getRow--

From https://stackoverflow.com/questions/64601558/itemreader-unable-to-read-rows-via-prestodriver

**Comment by jasonyanwenl** [comment]
Hi, I am a beginner to our Presto community and I would like to take a look at this issue since this is labeled as good first issue. Hopefully I could raise a PR for this. 

To fix this issue, I just would like to make sure that I need to maintain a counter indicating row number and return this number when `getRow` is called (and return 0 if there is no current row) , right?

Thanks!

**Comment by findepi** [comment]
@jasonyanwenl  welcome!
what you wrote sounds reasonable to me, although edge cases need to be verified (behavior before first the  row or after the last).
It would be good to double check and compare the proposed behavior with that of e.g. PostgreSQL JDBC driver.
