### ISSUE TITLE
Implement cast from array to varchar

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#593]
CLI renders arrays like Java `List`: `[e1, e2, ...]`.
This functionality could be also available in engine, in the form of a `cast` from `array(e)` to `varchar`.

**Comment by dain** [comment]
Is there a reason to not use cast to `JSON`?

**Comment by electrum** [comment]
The CLI rendering was more of an accident that worked well enough. The CLI gets the JSON converted to Java objects, then does `toString()` on them, so you get the Java format. Since it's intended for debugging, it has problems:

```
presto> select array['f, oo', 'bar'];
    _col0     
--------------
 [f, oo, bar] 
(1 row)
```

I've definitely thought about having a cast to varchar for structural types, and thought about it again for the `format` function, but it comes back to the question of what the format should be. @dain had a good point that a cast is typically reversible. Explicitly casting to JSON avoids this problem because it has a well defined format. The downside is that the syntax is complex:

```
presto> select json_format(cast(array['f, oo', 'bar'] as json));
      _col0      
-----------------
 ["f, oo","bar"] 
(1 row)
```

The output is also less readable than the Java variant. I see the usefulness in such a feature, but I'm not sure that cast to varchar is the right way. One thought is the `format` function could do this for structural types (currently it uses the cast to varchar operator which won't exist for these).

**Comment by findepi** [comment]
`json_format(cast(... as json))` is what I ended up doing.

Since it's not clear whether we want this or not, let me close the issue for now.

**Comment by dain** [comment]
What if we changed `json_format(JSON):varchar` to `json_format(T):varchar` where there exists `cast(T):JSON`?
