### ISSUE TITLE
io.prestosql.jdbc SocketTimeOut

### ISSUE THREAD

**Issue by WingsLong** [prestosql/presto#761]
OkHttpClient default readTimeout 10_000ms，how to set longer time

**Comment by Praveen2112** [comment]
Not sure whether it's configurable in the Presto JDBC APIs. But the `OkHttpClient` is built in the `PrestoDriver` so there we can set the custom `readTimeout` (Using `OkHttpClient.Builder#readTimeout`)

**Comment by WingsLong** [comment]
> Not sure whether it's configurable in the Presto JDBC APIs. But the `OkHttpClient` is built in the `PrestoDriver` so there we can set the custom `readTimeout` (Using `OkHttpClient.Builder#readTimeout`)

How to set this config with jdbc paramter? or just to change the source code then repackage

**Comment by Praveen2112** [comment]
I'm not sure whether it is configurable with the jdbc parameter. We can change the source code and repackage it which has the modified `readTimeout`.

**Comment by WingsLong** [comment]
> I'm not sure whether it is configurable with the jdbc parameter. We can change the source code and repackage it which has the modified `readTimeout`.

All right!THANK YOU~MY FRIEND!

**Comment by electrum** [comment]
Can you explain the problem you’re seeing that requires changing this? The Presto server should return a response after one second (so 2 seconds max accounting for network latency). If the request fails, the client will retry for 2 minutes by default.

**Comment by ssquan** [comment]
It may happen. 

Trino invokes the `getTable` method of hive client to get table info from HMS while generating an execution plan. `getTable` is a very heavy operation because hive needs to execute about 9 SQL to collect all information. If there are thousands of tables and millions of partitions, RPC latency will be seconds (9 seconds most in my product environment). Things get worse when multiple execution engines share a hive meta store. 

It’s hard to make HMS faster. Solutions like read-write separation、develop light RPCs, or use a faster backend database are not easy.  Add a read timeout parameter may be the fast way to overcome this problem.

**Comment by hackeryang** [comment]
> It may happen.
> 
> Trino invokes the `getTable` method of hive client to get table info from HMS while generating an execution plan. `getTable` is a very heavy operation because hive needs to execute about 9 SQL to collect all information. If there are thousands of tables and millions of partitions, RPC latency will be seconds (9 seconds most in my product environment). Things get worse when multiple execution engines share a hive meta store.
> 
> It’s hard to make HMS faster. Solutions like read-write separation、develop light RPCs, or use a faster backend database are not easy. Add a read timeout parameter may be the fast way to overcome this problem.

You can also try `Hive Metadata Cache` feature in Trino, please see: https://trino.io/docs/current/connector/metastores.html#general-metastore-configuration-properties
