### ISSUE TITLE
Phoenix Connector Lowercase Table/View could not be find

### ISSUE THREAD

**Issue by SimonWan1029** [prestosql/presto#858]
Once create a phoenix view which schema or table name is lowercased, then presto could not find  these table ;

**Comment by findepi** [comment]
Upon cursory reading of the source, I would assume this line might be responsible:
https://github.com/prestosql/presto/blob/b763176ff1c33bce413911908bda67b63ee5e2f4/presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcClient.java#L649-L652

If the uppercase is the default case for Phoenix, it may be it works as intended. JDBC-based connectors support case-insensitive name matching
https://github.com/prestosql/presto/blob/03bb0a426732f6ea947844dcc652a3ae2c76af1b/presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcConfig.java#L107-L112
It's not available for Phoenix though, as the connector does not bind/configure the `BaseJdbcConfig` object.

@vincentpoon would you like to take a look?

**Comment by vincentpoon** [comment]
For `DatabaseMetaData#storesUpperCaseIdentifiers`, Phoenix returns `true`, so by default unquoted identifiers are uppercased.

I think the issue here is with quoted identifiers.  My general recommendation would be to not use quoted mixed/lowercase identifiers.  Phoenix does support them, but certain areas can be confusing and/or not implemented well.  For example, both `PhoenixDatabaseMetaData#storesUpperCaseQuotedIdentifiers` and `PhoenixDatabaseMetaData#storesMixedCaseQuotedIdentifiers` return `true`.  But I'll see if we can support mixed case quoted here in the connector.

**Comment by findepi** [comment]
@vincentpoon proper support for case sensitive identifiers requires engine changes (https://github.com/prestosql/presto/issues/17).
Part of that will be to add case insensitive table name resolution when user does not quote the identifier in the query.
So when https://github.com/prestosql/presto/issues/17 is done, then:
1. `SELECT .. FROM "some_table"` in Presto ⇒ table needs to be exactly lower case (`some_table`)
2. `SELECT .. FROM "SOME_TABLE"` in Presto ⇒ table needs to be exactly upper case (`SOME_TABLE`)
3. `SELECT .. FROM some_table` in Presto ⇒ table needs to be `some_table` case _insensitively_ (`some_table`, `SomE_TabLe`, `SOME_TABLE`, etc.)

To support 3. the connector will need to be able to do case insensitive name resolution.
In JDBC connectors this is currently supported as an opt-in feature (the `case-insensitive-name-matching` configuration toggle).

Would it be possible to expose this functionality in Phoenix connector as well?
I guess you didn't bind `BaseJdbcConfig` in guice because not all its configuration toggles make sense.
Make we introduce a separate config class for the opt-in case insensitive name matching?

cc @electrum

**Comment by vincentpoon** [comment]
@SimonWan1029 @findepi  Check out #872 , which adds support for `case-insensitive-name-matching`

You'll need to add the following line into your phoenix catalog properties file:
`case-insensitive-name-matching=true`.  Then you should be able to query your case sensitive tables.
